//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Admin.Views.PageHandlers.FieldSelector {
    
    
    public partial class Default {
        
        /// <summary>
        /// GlobalFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GlobalFields;
        
        /// <summary>
        /// MediaTypeFieldsEditorWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MediaTypeFieldsEditorWrapper;
        
        /// <summary>
        /// MediaTypeFieldsEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplication.Admin.Controls.Editors.MediaTypeFieldsEditor MediaTypeFieldsEditor;
        
        /// <summary>
        /// MediaDetailFieldsEditorWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MediaDetailFieldsEditorWrapper;
        
        /// <summary>
        /// FieldsTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplication.Admin.Controls.MediaTypes.Common.Tabs.FieldsTab FieldsTab;
    }
}
