//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Field
    {
        public long ID { get; set; }
        public string FieldCode { get; set; }
        public string FieldLabel { get; set; }
        public string FieldValue { get; set; }
        public long OrderIndex { get; set; }
        public string FrontEndLayout { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string GroupName { get; set; }
        public bool RenderLabelAfterControl { get; set; }
        public string AdminControl { get; set; }
        public string GetAdminControlValue { get; set; }
        public string SetAdminControlValue { get; set; }
        public string FieldDescription { get; set; }
        public bool ShowFrontEndFieldEditor { get; set; }
    }
}
