//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldFile
    {
        public long ID { get; set; }
        public long MediaDetailFieldID { get; set; }
        public string Name { get; set; }
        public string PathToFile { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public int OrderIndex { get; set; }
        public string Description { get; set; }
    
        public virtual MediaDetailField MediaDetailsField { get; set; }
    }
}
