//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldType
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string CodeToRenderAdminControl { get; set; }
        public string CodeToGetAdminControlValue { get; set; }
        public string CodeToSetAdminControlValue { get; set; }
        public string CodeToRenderFrontEndLayout { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string FieldDescription { get; set; }
    }
}
