//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaDetailField : Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaDetailField()
        {
            this.FieldAssociations = new HashSet<FieldAssociation>();
        }
    
        public long MediaDetailID { get; set; }
        public Nullable<long> MediaTypeFieldID { get; set; }
        public bool UseMediaTypeFieldFrontEndLayout { get; set; }
        public bool UseMediaTypeFieldDescription { get; set; }
    
        public virtual MediaDetail MediaDetail { get; set; }
        public virtual MediaTypeField MediaTypeField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldAssociation> FieldAssociations { get; set; }
    }
}
