//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlRedirectRule : MediaDetail
    {
        public string VirtualPathToRedirect { get; set; }
        public string RedirectToUrl { get; set; }
        public bool Is301Redirect { get; set; }
    }
}
