//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMedia
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long MediaID { get; set; }
        public long PermissionID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
    }
}
