//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Admin.Controls.MediaTypes.Common.Tabs {
    
    
    public partial class RolesUsersTab {
        
        /// <summary>
        /// MultiRoleSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplication.Admin.Controls.Selectors.MultiRolesSelector MultiRoleSelector;
        
        /// <summary>
        /// CanLimitedRolesAccessAllChildPages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CanLimitedRolesAccessAllChildPages;
        
        /// <summary>
        /// EnforceRoleLimitationOnFrontEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox EnforceRoleLimitationOnFrontEnd;
    }
}
